// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {downloader} from '../models';

export function DeleteDownload(arg1:string,arg2:boolean):Promise<void>;

export function GetAllDownloads():Promise<Array<downloader.DownloadState>>;

export function GetSettings():Promise<downloader.Settings>;

export function ResumeDownload(arg1:string):Promise<void>;

export function StartDownload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StopDownload(arg1:string):Promise<void>;
