// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDownload(arg1, arg2) {
  return window['go']['main']['App']['DeleteDownload'](arg1, arg2);
}

export function GetAllDownloads() {
  return window['go']['main']['App']['GetAllDownloads']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function StartDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3);
}

export function StopDownload(arg1) {
  return window['go']['main']['App']['StopDownload'](arg1);
}
